version: '3.8'

services: 
  frontend:
    image: frontend
    container_name: frontend

  backend:
    image: backend
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres

  redis: 
    image: redis:alpine
    container_name: redis

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf