version: '3.8'

services: 
  frontend:
    build: 
      context: .
      dockerfile: /home/eeritvan/DevOps/part 1/1.14/frontend.Dockerfile
    container_name: frontend
    ports:
      - 5000:5000

  backend:
    build:
      context: .
      dockerfile: /home/eeritvan/DevOps/part 1/1.14/backend.Dockerfile
    container_name: backend
    ports:
      - 8080:8080