version: '3.8'

services: 
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - 5000:5000

  backend:
    image: backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis

  redis: 
    image: redis:7.0-alpine
    container_name: redis