version: '3.8'

services:
  app: 
    image: eeritvan/devops-express
    ports:
      - 8080:8080
    container_name: app

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
