version: '3.8'

services: 
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - 5000:5000

  backend:
    image: backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres

  redis: 
    image: redis:alpine
    container_name: redis

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres