name: Release Node.js app

on:
  push:
    branches:
      - main
      - "part3/3.1"

jobs:
  build:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Build
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: part 3/3.1/express-app/Dockerfile
          push: true
          tags: eeritvan/devops-express:latest